#
# Standard configuration
#
baseURL                = "https://website.mianitianoustudy.com"
copyright              = "The MIT License (MIT) Copyright © 2022 Kieran Collins"
defaultContentLanguage = "en"
enableEmoji            = false
enableGitInfo          = true
metaDataFormat         = "yaml"
publishDir             = "public"
title                  = "Kieran Collins OU Study Notes"
theme                  = "shadocs"
themesDir = "themes"

[Author]
  name = "Kieran Collins"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.91.0'
    max = ''
  [[module.mounts]]
    source = 'asyncapi'
    target = 'static/asyncapi'
  [[module.mounts]]
    source = 'openapi'
    target = 'static/openapi'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = false

[Languages]
  [Languages.en]
    contentDir   = "content/english"
    title        = "Kieran Collins OU Study Notes"
    weight       = 1
    languageName = "English"

  [Languages.fr]
    contentDir   = "content/french"
    title        = "Kieran Collins OU Notes d'étude"
    weight       = 2
    languageName = "Français"

  [Languages.is]
    contentDir   = "content/icelandic"
    title        = "Kieran Collins OU rannsóknarskýringar"
    weight       = 3
    languageName = "Icelandic"  
  





#
# Specific configuration
#
[params]
  logo                    = "images/logo.png"
  logoTouch               = "images/logoTouch.png"
  image404                = "images/404.gif"
  favicon                 = "images/favicon.png"
  faviconmd               = "![Favicon](/images/favicon.png)"
  siteContentOrder        = "weight"
  # toc                   = true
  # globalBanner          = true
  currentVersion          = "latest"
  latestVersionUrl        = "https://website.mianitianoustudy.com/"
  # enforceRefrelLinks    = true
  [params.navbar.shortcuts]
    [params.navbar.shortcuts.example]
      keys     = ["Shift","1"]
      function = "scExample"
  [[params.navbar.versions]]
    name = 'latest'
    url  = 'https://website.mianitianoustudy.com/'
  [[params.navbar.versions]]
    name = 'deprecated version'
    url  = 'https://website.mianitianoustudy.com/404.html'
  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
      icon = "fa-solid fa-tag"
  [params.includes]
    jsModules = [
        "js/shortcuts.js"
      ]
    js        = []
    css       = [
        "css/shortcuts.css"
      ]
  [params.versions]
    hugo_min         = "[0.91.0](https://github.com/gohugoio/hugo/releases/tag/v0.91.0)"
    bulma            = "[0.9.3](https://github.com/jgthms/bulma/releases/tag/0.9.3)"
